# Generated by Django 3.1.4 on 2021-05-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish',
            new_name='publisher',
        ),
    ]
